[build]
  publish = "frontend"

[functions]
  directory = "netlify/functions"

# Rule for API requests (MUST BE FIRST)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Rule for Single Page Application (SPA) - general catch-all (MUST BE LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
